modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="spatialminer"
version="1.0.0"
displayName="Spatial Miner"
authors="RuskElly"
description='''
Adds battery blocks, miners from ghost dimension, cables and protection system with energy network.
'''

[[dependencies.spatialminer]]
modId="neoforge"
type="required"
versionRange="[21.1.232,)"
ordering="NONE"
side="BOTH"

[[dependencies.spatialminer]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"